### ISSUE TITLE
The httpPort property from server settings contains the host too.

### ISSUE THREAD

**Issue by Szauka** [Romakita/ts-express-decorators#408]
Type | Version
Bug|4.25

****

## Description
When the port number is 0 and it gets assigned by the OS, when accessing the httpPort property it contains the host too. 
for example 0.0.0.0:61809

I would expect the httpPort to contain only the the port number.

thanks a lot for the great work you doing.

**Comment by Romakita** [comment]
fixed

**Comment by Szauka** [comment]
Hi @Romakita ,

This is still happening on latest version of master. 

I think it is because of this:  https://github.com/Romakita/ts-express-decorators/blob/b7145079ef127550add1f6a358ab75f3b9f62d33/src/common/config/services/ServerSettingsService.ts#L471-L473

The **httpPort** is set to be "**address:port**" so when I call `this.settings.httpPort` in `$onReady` it returns host+port, not only **port**.

Is this a **bug**? or it works as intended?

Thank you, 
Dumitru

**Comment by Romakita** [comment]
Sorry bad response on this issue. The httpPort can contain a host + port when the configuration is setup on ServerSettings decorator. By convention, I always store the host + port. 

You can use this method: `ServerSettingsService.getHttpPort(): {address, port}`

See you,
Romain

**Comment by Szauka** [comment]
I see, that is ok, I was just wandering if it'a bug or not, but if you store them together by default that is alright.
